version: '3.0'
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - 5432:5432
  flask_app:
    container_name: flask_app
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
  vite_app:
    container_name: vite_app
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
